#Site settings
title: ABei Blog
SEOTitle: 阿贝的博客 | ABei Blog
email: jeepchenup@foxmail.com
description: keep living, keep coding.
baseurl: "" 
header-img: img/home-bg.jpg


# Build settings
markdown: kramdown
port: 3000                       #for debug page
paginate: 10

#Sitebar settings
sitebar: true                      #whether or not using Sitebar.
sidebar-about-description: 业精于勤荒于嬉，<br/>行成于思毁于随。
sidebar-avatar: /img/avatar-abei.jpg

#SNS settings
RSS: false
github_username:  jeepchenup
linkedin_username: abeidragon


# Featured Tags
featured-tags: true                # whether or not using Feature-Tags.
featured-condition-size: 0         # 标签的长度大于[featured-condition-size]所指定的长度时候成为标签.

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# please use-> "bundle install"

plugins: [jekyll-paginate]