#Site settings
title: ABei Bolg
email: jeepchenup@foxmail.com
description: one life, one code.
baseurl: "" 
header-img: img/home-bg.jpg
RSS: false
github_username:  jeepchenup

# Build settings
markdown: kramdown
port: 3000