#Site settings
title: ABei Bolg
email: jeepchenup@foxmail.com
description: one life, one code.
baseurl: "" 
header-img: img/home-bg.jpg
RSS: false
github_username:  jeepchenup

# Build settings
markdown: kramdown
port: 3000

# Featured Tags
featured-tags: true               # whether or not using Feature-Tags
featured-condition-size: 1         # A tag will be featured if the size of it is more than this condition value